# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Kwiki-RecentChangesRSS
version:      0.06
version_from: lib/Kwiki/RecentChangesRSS.pm
installdirs:  site
requires:
    Kwiki:                         0.33
    Test::More:                    0
    XML::RSS:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
